# Generated by Django 3.0.5 on 2020-04-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('RollNo', models.IntegerField(default=None)),
                ('Email', models.EmailField(default=None, max_length=254)),
                ('Subject', models.CharField(default=None, max_length=100, null=True)),
                ('Time_of_Submission', models.TimeField(auto_now=True)),
                ('Assignment', models.FileField(upload_to='')),
            ],
        ),
    ]
